name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read

jobs:
  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Rust (nightly + rustfmt)
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly
          components: rustfmt
      - name: Generate Cargo.lock (if missing)
        run: |
          if [ ! -f Cargo.lock ]; then
            cargo generate-lockfile
          fi
      - name: Cargo fmt check
        run: cargo fmt -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install system dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y --no-install-recommends \
            pkg-config build-essential cmake libfreetype6-dev
      - name: Install Rust (stable + clippy)
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: clippy
      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: |-
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-stable-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-stable-
            ${{ runner.os }}-cargo-
      - name: Generate Cargo.lock (if missing)
        run: |
          if [ ! -f Cargo.lock ]; then
            cargo generate-lockfile
          fi
      - name: Cargo clippy (deny warnings)
        run: cargo clippy --all-targets --all-features -- -D warnings

  build-test:
    name: Build & Test (Linux)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install system dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y --no-install-recommends \
            pkg-config build-essential cmake libfreetype6-dev
      - name: Install Rust (stable)
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: |-
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-stable-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-stable-
            ${{ runner.os }}-cargo-
      - name: Generate Cargo.lock (if missing)
        run: |
          if [ ! -f Cargo.lock ]; then
            cargo generate-lockfile
          fi
      - name: Build
        run: cargo build --verbose
      - name: Test
        run: cargo test --verbose
      - name: Doc (ensure docs build)
        run: cargo doc --no-deps --verbose
